require "rest-client"
require "nokogiri"
require "yaml"
require "time"
require "rchardet19"
require "csv"
require "iconv"

require "timeedit/version"
require "timeedit/rooms"
require "timeedit/bookings"